#This file was originally generated by PyScripter's unitest wizard

import unittest
import db_config

class TestConfigTable(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_create_table(self):
        pass

    def test_load_table(self):
        pass

    def testinsert(self):
        pass

    def testget_symbols(self):
        pass

if __name__ == '__main__':
    unittest.main()
