#This file was originally generated by PyScripter's unitest wizard

import unittest
import yql

class TestYql(unittest.TestCase):

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testquery_yql(self):
        lis = []
        fields = []
        fields.append('Symbol')
        fields.append('YearLow')
        fields.append('LastTradePriceOnly')
        fields.append('YearHigh')
        fields.append('LastTradeDate')
        fields.append('Bid')
        fields.append('PreviousClose')
        fields.append('PercentChange')
        fields.append('Ask')
        fields.append('Change')
        fields.append('Name')
        fields.append('DaysRange')
        fields.append('LastTradeTime')
        fields.append('StockExchange')
        fields.append('DaysHigh')
        fields.append('Open')

        lis.append("TCS.NS")
        lis.append("HINDALCO.NS")
        yql_ob = yql.Yql(lis, fields )
        print yql_ob.query_yql()


if __name__ == '__main__':
    unittest.main()
